host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Example usage of Go with Gin and Postgres with relations like one to
    many, many to many
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-Gin-Postgres-Relations
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
